### ISSUE TITLE
Support Trace Functionality

### ISSUE THREAD

**Issue by milky2028** [ngxs/devtools#78]
Vanilla Redux Devtools [supports stack traces](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Features/Trace.md) in actions as of 12/18/2018. The trace option is disabled by default, due to potential performance issues. The trace API also supports an option that limits the number of traces.

It would be fantastic to have this feature available as a configurable option! Something similar to this:

``` javascript
NgxsReduxDevtoolsPluginModule.forRoot({ disabled: !environment.production, trace: true, traceLimit: 25 })
```

**Comment by splincode** [comment]
PR please))

**Comment by milky2028** [comment]
I think I actually meant to submit this on the main repo, I didn't realize that this was a separate project and that the store repo is what contains the current code that integrates with the Redux Devtools extension. I'll see if I can submit a repo there.
